# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/Users/nk/Development/scratch/libosmscout-code/libosmscout/src/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/Users/nk/Development/scratch/libosmscout-code/libosmscout/./include"
package="libosmscout"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libosmscout"
;; --help) pkg-config --help ; echo Buildscript Of "libosmscout base library"
;; --modversion|--version) echo "0.1"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "-std=c++0x -I/usr/local/Cellar/marisa/0.2.4/include" "-losmscout -L/usr/local/Cellar/marisa/0.2.4/lib -lmarisa"
:
;; --cflags) echo -I${includedir} "-std=c++0x -I/usr/local/Cellar/marisa/0.2.4/include"
:
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
